### ISSUE TITLE
Education Ramp-up 

### ISSUE THREAD

**Issue by cheri-dean** [catthorn/github-slideshow#4]
Hey @blkdm0n I have a goal to have a *conversational* understanding of the following topics by **Monday the 17th**.  Please let me know if you have any tips or see any features I’ve overlooked. :stuck_out_tongue_winking_eye:

-	[x] Markdown Syntax
-	[x] GitHub Workflow 
o	Create Repository
o	Add Commits
o	Open Pull Request
o	Discuss and Review
o	Code
o	Deploy
o	Merge
-	[x] Issues
-	[x] Actions
-	[x] Packages
-	[x] Codespaces
-	[x] DevOps
-	[x] DevSecOps

**Comment by blkdm0n** [comment]
Hey @cheri-dean this looks like a comprehensive overview of GitHub and it's features.  I'm happy to help where I can if you should have questions.  Just give a shout!  👍

**Comment by cheri-dean** [comment]
I'm closing the issue, as I now have a comfortable level of understanding of all topics.

**Comment by blkdm0n** [comment]
Sounds good, but I notice you didn't check all the boxes.  Small nit pick!

**Comment by cheri-dean** [comment]
Great callout blkdm0m!  Thanks for the nit pick 😄
